site_name: Docs
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

nav:
  - Home: index.md
  - Homelab:
    - Overview: homelab/index.md
    - Server Rack: homelab/server-rack.md
    - Servers:
      - Overview: homelab/servers/index.md
      - cp0101: homelab/servers/cp0101.md
      - cp0102: homelab/servers/cp0102.md
      - cp0103: homelab/servers/cp0103.md
      - cp0104: homelab/servers/cp0104.md
      - cp0105: homelab/servers/cp0105.md
    - Network: homelab/network.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
