site_name: Docs
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

nav:
  - Home: index.md
  - Homelab:
    - Overview: homelab/index.md
    - Server Rack: homelab/server-rack.md
    - Servers:
      - Overview: homelab/servers/index.md
      - CP0101: homelab/servers/CP0101.md
      - CP0102: homelab/servers/CP0102.md
      - CP0103: homelab/servers/CP0103.md
      - CP0104: homelab/servers/CP0104.md
      - CP0105: homelab/servers/CP0105.md
    - Network: homelab/network.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
